version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: run
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: always

  migrate:
        image: migrate/migrate
        volumes:
            - ./database/migrations:/migrations
        command: ["-path", "/migrations", "-database",  "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=disable", "up"]
        depends_on:
          db:
            condition: service_healthy
        links: 
            - db
  db:
    image: postgres
    volumes:
      - sqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  sqldata: